# 1. Data Gathering / Import Libraries

In [1]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# For linear regression with numerical variables
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

from scipy import stats
from sklearn.impute import SimpleImputer

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
# loading dataframe from csv file
df = pd.read_csv('/Users/lenovo1/Downloads/Mid_bootcamp_project/fifa21_male2.csv')
df.head()

/var/folders/mm/cjv4cnl90rz3rsp85pkv7wk80000gp/T/ipykernel_57850/2108361933.py:2: DtypeWarning: Columns (78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/lenovo1/Downloads/Mid_bootcamp_project/fifa21_male2.csv')

,ID,Name,Age,OVA,Nationality,Club,BOV,BP,Position,Player Photo,Club Logo,Flag Photo,POT,Team & Contract,Height,Weight,foot,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Contract,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,LS,ST,RS,LW,LF,CF,RF,RW,LAM,CAM,RAM,LM,LCM,CM,RCM,RM,LWB,LDM,CDM,RDM,RWB,LB,LCB,CB,RCB,RB,GK,Gender
0,2,G. Pasquale,33,69,Italy,Udinese,71,LWB,LM,https://cdn.sofifa.com/players/000/002/16_120.png,https://cdn.sofifa.com/teams/55/light_60.png,https://cdn.sofifa.com/flags/it.png,69,Udinese 2008 ~ 2016,"6'0""",181lbs,Left,0,"Jul 1, 2008",NaN,€625K,€7K,€0,2008 ~ 2016,313,75,50,59,71,58.0,338,73,65.0,60,69,71,347,68,74,68.0,69,68.0,347,74,68.0,69,68,68,320,72,69.0,63.0,66.0,50,NaN,208,70,69,69.0,56,14,5,15,10,12,1929,408,3 ★,2★,Medium,High,2 ★,71,59,70,71,68,69,4,65+0,65+0,65+0,68+0,67+0,67+0,67+0,68+0,68+0,68+0,68+0,69+0,69+0,69+0,69+0,69+0,71+-2,70+-1,70+-1,70+-1,71+-2,70+-1,69+0,69+0,69+0,70+-1,17+0,Male
1,16,Luis García,37,71,Spain,KAS Eupen,70,CM,CM CAM CDM,https://cdn.sofifa.com/players/000/016/19_120.png,https://cdn.sofifa.com/teams/2013/light_60.png,https://cdn.sofifa.com/flags/es.png,71,KAS Eupen 2014 ~ 2019,"5'10""",143lbs,Right,0,"Jul 19, 2014",NaN,€600K,€7K,€1.1M,2014 ~ 2019,337,68,64,61,76,68.0,369,69,79.0,79,71,71,305,56,50,62.0,65,72.0,324,75,54.0,64,60,71,362,71,71.0,72.0,73.0,75,79.0,153,70,43,40.0,56,9,12,13,11,11,1906,385,4 ★,3★,Medium,Medium,1 ★,53,69,73,69,58,63,4,67+1,67+1,67+1,67+0,68+0,68+0,68+0,67+0,70+1,70+1,70+1,68+1,70+1,70+1,70+1,68+1,62+1,66+1,66+1,66+1,62+1,60+1,60+1,60+1,60+1,60+1,17+1,Male
2,27,J. Cole,33,71,England,Coventry City,71,CAM,CAM RM RW LM,https://cdn.sofifa.com/players/000/027/16_120.png,https://cdn.sofifa.com/teams/1800/light_60.png,https://cdn.sofifa.com/flags/gb-eng.png,71,Coventry City 2016 ~ 2020,"5'9""",161lbs,Right,0,"Jan 7, 2016",NaN,€1.1M,€15K,€0,2016 ~ 2020,337,80,64,41,77,75.0,387,79,84.0,77,69,78,295,48,42,71.0,59,75.0,284,72,58.0,29,56,69,317,69,39.0,69.0,74.0,66,NaN,99,35,34,30.0,51,9,6,13,16,7,1770,354,4 ★,4★,Medium,Low,2 ★,45,68,76,77,36,52,11,64+0,64+0,64+0,70+0,69+0,69+0,69+0,70+0,71+0,71+0,71+0,68+0,66+0,66+0,66+0,68+0,52+0,54+0,54+0,54+0,52+0,47+0,46+0,46+0,46+0,47+0,15+0,Male
3,36,D. Yorke,36,68,Trinidad &amp; Tobago,Sunderland,70,ST,NaN,https://cdn.sofifa.com/players/000/036/09_120.png,https://cdn.sofifa.com/teams/106/light_60.png,https://cdn.sofifa.com/flags/tt.png,82,Sunderland 2009,"5'11""",165lbs,Right,14,NaN,NaN,€0,€0,€0,2009,264,54,70,60,80,NaN,255,68,NaN,46,64,77,176,59,62,NaN,55,NaN,239,63,NaN,51,66,59,271,59,70.0,72.0,NaN,70,NaN,75,34,41,NaN,68,5,21,64,21,21,1348,369,3 ★,1★,NaN,NaN,1 ★,61,66,66,69,47,60,3,67+0,67+0,67+0,66+0,67+0,67+0,67+0,66+0,70+0,70+0,70+0,66+0,68+0,68+0,68+0,66+0,56+0,65+0,65+0,65+0,56+0,57+0,51+0,51+0,51+0,57+0,22+0,Male
4,41,Iniesta,36,81,Spain,Vissel Kobe,82,CAM,CM CAM,https://cdn.sofifa.com/players/000/041/20_120.png,https://cdn.sofifa.com/teams/101146/light_60.png,https://cdn.sofifa.com/flags/es.png,81,Vissel Kobe 2018 ~ 2021,"5'7""",150lbs,Right,0,"Jul 16, 2018",NaN,€5.5M,€12K,€7.2M,2018 ~ 2021,367,75,69,54,90,79.0,408,85,80.0,70,83,90,346,61,56,79.0,75,75.0,297,67,40.0,58,62,70,370,58,70.0,78.0,93.0,71,89.0,181,68,57,56.0,45,6,13,6,13,7,2014,420,4 ★,4★,High,Medium,4 ★,58,70,85,85,63,59,149,72+3,72+3,72+3,79+0,79+0,79+0,79+0,79+0,82+-1,82+-1,82+-1,79+2,81+0,81+0,81+0,79+2,70+3,73+3,73+3,73+3,70+3,67+3,64+3,64+3,64+3,67+3,17+3,Male

In [3]:
# Taking a look at the size of the dataframe
print("Number of rows: ", df.shape[0])
print("Number of columns: ", df.shape[1])

Number of rows:  17125
Number of columns:  107

# 2. Data Pre-processing

# 2.1 Cleaning column names

In [4]:
# Checking column names
print(df.columns.tolist()) # list ALL column names for observation

['ID', 'Name', 'Age', 'OVA', 'Nationality', 'Club', 'BOV', 'BP', 'Position', 'Player Photo', 'Club Logo', 'Flag Photo', 'POT', 'Team & Contract', 'Height', 'Weight', 'foot', 'Growth', 'Joined', 'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Contract', 'Attacking', 'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'GK', 'Gender']

In [5]:
# Create dictionary to replace abbreviations in columns for easier understanding throughout the analysis
new_col_name = {'OVA': 'overall', 
                'BOV': 'best_overall', 
                'BP': 'best_position', 
                'POT': 'potential',
                'FK Accuracy': 'free_kick_acc',
                'W/F': 'weak_foot',
                'SM': 'skill_moves',
                'A/W': 'away_win',
                'D/W': 'duels_won', 
                'IR': 'international_reputation',
                'PAC': 'pace',
                'SHO': 'shooting',
                'PAS': 'passing', 
                'DRI': 'dribbling2',
                'DEF':'defense',
                'PHY':'physicality',
                'LS':'left_stick',
                'ST':'striker',
                'RS':'right_stick',
                'LW':'left_wing',
                'LF':'left_forward',
                'CF':'centre_forward',
                'RF':'right_forward',
                'RW':'right_wing',
                'LAM':'left_attacking_midfielder',
                'CAM':'central_attacking_midfielder',
                'RAM':'right_attacking_midfielder',
                'LCM':'left_centre_midfield',
                'CM':'central_midfielder',
                'RCM':'right_centre_midfield',
                'RM':'right_midfielder',
                'LWB': 'left_wing_back',
                'LDM': 'left_defensive_midfielder',
                'CDM': 'center_defensive_midfielder',
                'RDM': 'right_defensive_midfielder',
                'RWB': 'right_wing_back',
                'LB': 'left_back',
                'LCB' : 'left_center_back',
                'CB' : 'center_back',
                'RCB' : 'right_center_back',
                'RB' : 'right_back',
                'GK': 'goalkeeper',
                'LAM': 'left_attacking_midfield',
                'CAM': 'center_attacking_midfielder', 
                'RAM': 'right_attacking_midfielder', 
                'LM': 'linesman'}
display(new_col_name)

{'OVA': 'overall',
 'BOV': 'best_overall',
 'BP': 'best_position',
 'POT': 'potential',
 'FK Accuracy': 'free_kick_acc',
 'W/F': 'weak_foot',
 'SM': 'skill_moves',
 'A/W': 'away_win',
 'D/W': 'duels_won',
 'IR': 'international_reputation',
 'PAC': 'pace',
 'SHO': 'shooting',
 'PAS': 'passing',
 'DRI': 'dribbling2',
 'DEF': 'defense',
 'PHY': 'physicality',
 'LS': 'left_stick',
 'ST': 'striker',
 'RS': 'right_stick',
 'LW': 'left_wing',
 'LF': 'left_forward',
 'CF': 'centre_forward',
 'RF': 'right_forward',
 'RW': 'right_wing',
 'LAM': 'left_attacking_midfield',
 'CAM': 'center_attacking_midfielder',
 'RAM': 'right_attacking_midfielder',
 'LCM': 'left_centre_midfield',
 'CM': 'central_midfielder',
 'RCM': 'right_centre_midfield',
 'RM': 'right_midfielder',
 'LWB': 'left_wing_back',
 'LDM': 'left_defensive_midfielder',
 'CDM': 'center_defensive_midfielder',
 'RDM': 'right_defensive_midfielder',
 'RWB': 'right_wing_back',
 'LB': 'left_back',
 'LCB': 'left_center_back',
 'CB': 'center_back',
 'RCB': 'right_center_back',
 'RB': 'right_back',
 'GK': 'goalkeeper',
 'LM': 'linesman'}

In [6]:
# Rename columns
df.rename(columns = new_col_name, inplace=True)
df.head()

,ID,Name,Age,overall,Nationality,Club,best_overall,best_position,Position,Player Photo,Club Logo,Flag Photo,potential,Team & Contract,Height,Weight,foot,Growth,Joined,Loan Date End,Value,Wage,Release Clause,Contract,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,free_kick_acc,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,weak_foot,skill_moves,away_win,duels_won,international_reputation,pace,shooting,passing,dribbling2,defense,physicality,Hits,left_stick,striker,right_stick,left_wing,left_forward,centre_forward,right_forward,right_wing,left_attacking_midfield,center_attacking_midfielder,right_attacking_midfielder,linesman,left_centre_midfield,central_midfielder,right_centre_midfield,right_midfielder,left_wing_back,left_defensive_midfielder,center_defensive_midfielder,right_defensive_midfielder,right_wing_back,left_back,left_center_back,center_back,right_center_back,right_back,goalkeeper,Gender
0,2,G. Pasquale,33,69,Italy,Udinese,71,LWB,LM,https://cdn.sofifa.com/players/000/002/16_120.png,https://cdn.sofifa.com/teams/55/light_60.png,https://cdn.sofifa.com/flags/it.png,69,Udinese 2008 ~ 2016,"6'0""",181lbs,Left,0,"Jul 1, 2008",NaN,€625K,€7K,€0,2008 ~ 2016,313,75,50,59,71,58.0,338,73,65.0,60,69,71,347,68,74,68.0,69,68.0,347,74,68.0,69,68,68,320,72,69.0,63.0,66.0,50,NaN,208,70,69,69.0,56,14,5,15,10,12,1929,408,3 ★,2★,Medium,High,2 ★,71,59,70,71,68,69,4,65+0,65+0,65+0,68+0,67+0,67+0,67+0,68+0,68+0,68+0,68+0,69+0,69+0,69+0,69+0,69+0,71+-2,70+-1,70+-1,70+-1,71+-2,70+-1,69+0,69+0,69+0,70+-1,17+0,Male
1,16,Luis García,37,71,Spain,KAS Eupen,70,CM,CM CAM CDM,https://cdn.sofifa.com/players/000/016/19_120.png,https://cdn.sofifa.com/teams/2013/light_60.png,https://cdn.sofifa.com/flags/es.png,71,KAS Eupen 2014 ~ 2019,"5'10""",143lbs,Right,0,"Jul 19, 2014",NaN,€600K,€7K,€1.1M,2014 ~ 2019,337,68,64,61,76,68.0,369,69,79.0,79,71,71,305,56,50,62.0,65,72.0,324,75,54.0,64,60,71,362,71,71.0,72.0,73.0,75,79.0,153,70,43,40.0,56,9,12,13,11,11,1906,385,4 ★,3★,Medium,Medium,1 ★,53,69,73,69,58,63,4,67+1,67+1,67+1,67+0,68+0,68+0,68+0,67+0,70+1,70+1,70+1,68+1,70+1,70+1,70+1,68+1,62+1,66+1,66+1,66+1,62+1,60+1,60+1,60+1,60+1,60+1,17+1,Male
2,27,J. Cole,33,71,England,Coventry City,71,CAM,CAM RM RW LM,https://cdn.sofifa.com/players/000/027/16_120.png,https://cdn.sofifa.com/teams/1800/light_60.png,https://cdn.sofifa.com/flags/gb-eng.png,71,Coventry City 2016 ~ 2020,"5'9""",161lbs,Right,0,"Jan 7, 2016",NaN,€1.1M,€15K,€0,2016 ~ 2020,337,80,64,41,77,75.0,387,79,84.0,77,69,78,295,48,42,71.0,59,75.0,284,72,58.0,29,56,69,317,69,39.0,69.0,74.0,66,NaN,99,35,34,30.0,51,9,6,13,16,7,1770,354,4 ★,4★,Medium,Low,2 ★,45,68,76,77,36,52,11,64+0,64+0,64+0,70+0,69+0,69+0,69+0,70+0,71+0,71+0,71+0,68+0,66+0,66+0,66+0,68+0,52+0,54+0,54+0,54+0,52+0,47+0,46+0,46+0,46+0,47+0,15+0,Male
3,36,D. Yorke,36,68,Trinidad &amp; Tobago,Sunderland,70,ST,NaN,https://cdn.sofifa.com/players/000/036/09_120.png,https://cdn.sofifa.com/teams/106/light_60.png,https://cdn.sofifa.com/flags/tt.png,82,Sunderland 2009,"5'11""",165lbs,Right,14,NaN,NaN,€0,€0,€0,2009,264,54,70,60,80,NaN,255,68,NaN,46,64,77,176,59,62,NaN,55,NaN,239,63,NaN,51,66,59,271,59,70.0,72.0,NaN,70,NaN,75,34,41,NaN,68,5,21,64,21,21,1348,369,3 ★,1★,NaN,NaN,1 ★,61,66,66,69,47,60,3,67+0,67+0,67+0,66+0,67+0,67+0,67+0,66+0,70+0,70+0,70+0,66+0,68+0,68+0,68+0,66+0,56+0,65+0,65+0,65+0,56+0,57+0,51+0,51+0,51+0,57+0,22+0,Male
4,41,Iniesta,36,81,Spain,Vissel Kobe,82,CAM,CM CAM,https://cdn.sofifa.com/players/000/041/20_120.png,https://cdn.sofifa.com/teams/101146/light_60.png,https://cdn.sofifa.com/flags/es.png,81,Vissel Kobe 2018 ~ 2021,"5'7""",150lbs,Right,0,"Jul 16, 2018",NaN,€5.5M,€12K,€7.2M,2018 ~ 2021,367,75,69,54,90,79.0,408,85,80.0,70,83,90,346,61,56,79.0,75,75.0,297,67,40.0,58,62,70,370,58,70.0,78.0,93.0,71,89.0,181,68,57,56.0,45,6,13,6,13,7,2014,420,4 ★,4★,High,Medium,4 ★,58,70,85,85,63,59,149,72+3,72+3,72+3,79+0,79+0,79+0,79+0,79+0,82+-1,82+-1,82+-1,79+2,81+0,81+0,81+0,79+2,70+3,73+3,73+3,73+3,70+3,67+3,64+3,64+3,64+3,67+3,17+3,Male

In [7]:
# Standardize column names (lowercase, replace spaces with underscore)
def standard_cols(dataframe):
    '''Standardize column names into lowercase and replace spaces with underscore.'''
    dataframe.columns = [col.lower().replace(' ','_') for col in dataframe.columns]

standard_cols(df)
df.head()

,id,name,age,overall,nationality,club,best_overall,best_position,position,player_photo,club_logo,flag_photo,potential,team_&_contract,height,weight,foot,growth,joined,loan_date_end,value,wage,release_clause,contract,attacking,crossing,finishing,heading_accuracy,short_passing,volleys,skill,dribbling,curve,free_kick_acc,long_passing,ball_control,movement,acceleration,sprint_speed,agility,reactions,balance,power,shot_power,jumping,stamina,strength,long_shots,mentality,aggression,interceptions,positioning,vision,penalties,composure,defending,marking,standing_tackle,sliding_tackle,goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,total_stats,base_stats,weak_foot,skill_moves,away_win,duels_won,international_reputation,pace,shooting,passing,dribbling2,defense,physicality,hits,left_stick,striker,right_stick,left_wing,left_forward,centre_forward,right_forward,right_wing,left_attacking_midfield,center_attacking_midfielder,right_attacking_midfielder,linesman,left_centre_midfield,central_midfielder,right_centre_midfield,right_midfielder,left_wing_back,left_defensive_midfielder,center_defensive_midfielder,right_defensive_midfielder,right_wing_back,left_back,left_center_back,center_back,right_center_back,right_back,goalkeeper,gender
0,2,G. Pasquale,33,69,Italy,Udinese,71,LWB,LM,https://cdn.sofifa.com/players/000/002/16_120.png,https://cdn.sofifa.com/teams/55/light_60.png,https://cdn.sofifa.com/flags/it.png,69,Udinese 2008 ~ 2016,"6'0""",181lbs,Left,0,"Jul 1, 2008",NaN,€625K,€7K,€0,2008 ~ 2016,313,75,50,59,71,58.0,338,73,65.0,60,69,71,347,68,74,68.0,69,68.0,347,74,68.0,69,68,68,320,72,69.0,63.0,66.0,50,NaN,208,70,69,69.0,56,14,5,15,10,12,1929,408,3 ★,2★,Medium,High,2 ★,71,59,70,71,68,69,4,65+0,65+0,65+0,68+0,67+0,67+0,67+0,68+0,68+0,68+0,68+0,69+0,69+0,69+0,69+0,69+0,71+-2,70+-1,70+-1,70+-1,71+-2,70+-1,69+0,69+0,69+0,70+-1,17+0,Male
1,16,Luis García,37,71,Spain,KAS Eupen,70,CM,CM CAM CDM,https://cdn.sofifa.com/players/000/016/19_120.png,https://cdn.sofifa.com/teams/2013/light_60.png,https://cdn.sofifa.com/flags/es.png,71,KAS Eupen 2014 ~ 2019,"5'10""",143lbs,Right,0,"Jul 19, 2014",NaN,€600K,€7K,€1.1M,2014 ~ 2019,337,68,64,61,76,68.0,369,69,79.0,79,71,71,305,56,50,62.0,65,72.0,324,75,54.0,64,60,71,362,71,71.0,72.0,73.0,75,79.0,153,70,43,40.0,56,9,12,13,11,11,1906,385,4 ★,3★,Medium,Medium,1 ★,53,69,73,69,58,63,4,67+1,67+1,67+1,67+0,68+0,68+0,68+0,67+0,70+1,70+1,70+1,68+1,70+1,70+1,70+1,68+1,62+1,66+1,66+1,66+1,62+1,60+1,60+1,60+1,60+1,60+1,17+1,Male
2,27,J. Cole,33,71,England,Coventry City,71,CAM,CAM RM RW LM,https://cdn.sofifa.com/players/000/027/16_120.png,https://cdn.sofifa.com/teams/1800/light_60.png,https://cdn.sofifa.com/flags/gb-eng.png,71,Coventry City 2016 ~ 2020,"5'9""",161lbs,Right,0,"Jan 7, 2016",NaN,€1.1M,€15K,€0,2016 ~ 2020,337,80,64,41,77,75.0,387,79,84.0,77,69,78,295,48,42,71.0,59,75.0,284,72,58.0,29,56,69,317,69,39.0,69.0,74.0,66,NaN,99,35,34,30.0,51,9,6,13,16,7,1770,354,4 ★,4★,Medium,Low,2 ★,45,68,76,77,36,52,11,64+0,64+0,64+0,70+0,69+0,69+0,69+0,70+0,71+0,71+0,71+0,68+0,66+0,66+0,66+0,68+0,52+0,54+0,54+0,54+0,52+0,47+0,46+0,46+0,46+0,47+0,15+0,Male
3,36,D. Yorke,36,68,Trinidad &amp; Tobago,Sunderland,70,ST,NaN,https://cdn.sofifa.com/players/000/036/09_120.png,https://cdn.sofifa.com/teams/106/light_60.png,https://cdn.sofifa.com/flags/tt.png,82,Sunderland 2009,"5'11""",165lbs,Right,14,NaN,NaN,€0,€0,€0,2009,264,54,70,60,80,NaN,255,68,NaN,46,64,77,176,59,62,NaN,55,NaN,239,63,NaN,51,66,59,271,59,70.0,72.0,NaN,70,NaN,75,34,41,NaN,68,5,21,64,21,21,1348,369,3 ★,1★,NaN,NaN,1 ★,61,66,66,69,47,60,3,67+0,67+0,67+0,66+0,67+0,67+0,67+0,66+0,70+0,70+0,70+0,66+0,68+0,68+0,68+0,66+0,56+0,65+0,65+0,65+0,56+0,57+0,51+0,51+0,51+0,57+0,22+0,Male
4,41,Iniesta,36,81,Spain,Vissel Kobe,82,CAM,CM CAM,https://cdn.sofifa.com/players/000/041/20_120.png,https://cdn.sofifa.com/teams/101146/light_60.png,https://cdn.sofifa.com/flags/es.png,81,Vissel Kobe 2018 ~ 2021,"5'7""",150lbs,Right,0,"Jul 16, 2018",NaN,€5.5M,€12K,€7.2M,2018 ~ 2021,367,75,69,54,90,79.0,408,85,80.0,70,83,90,346,61,56,79.0,75,75.0,297,67,40.0,58,62,70,370,58,70.0,78.0,93.0,71,89.0,181,68,57,56.0,45,6,13,6,13,7,2014,420,4 ★,4★,High,Medium,4 ★,58,70,85,85,63,59,149,72+3,72+3,72+3,79+0,79+0,79+0,79+0,79+0,82+-1,82+-1,82+-1,79+2,81+0,81+0,81+0,79+2,70+3,73+3,73+3,73+3,70+3,67+3,64+3,64+3,64+3,67+3,17+3,Male

In [8]:
# Double check cols
print(df.columns.tolist())

['id', 'name', 'age', 'overall', 'nationality', 'club', 'best_overall', 'best_position', 'position', 'player_photo', 'club_logo', 'flag_photo', 'potential', 'team_&_contract', 'height', 'weight', 'foot', 'growth', 'joined', 'loan_date_end', 'value', 'wage', 'release_clause', 'contract', 'attacking', 'crossing', 'finishing', 'heading_accuracy', 'short_passing', 'volleys', 'skill', 'dribbling', 'curve', 'free_kick_acc', 'long_passing', 'ball_control', 'movement', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance', 'power', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots', 'mentality', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure', 'defending', 'marking', 'standing_tackle', 'sliding_tackle', 'goalkeeping', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes', 'total_stats', 'base_stats', 'weak_foot', 'skill_moves', 'away_win', 'duels_won', 'international_reputation', 'pace', 'shooting', 'passing', 'dribbling2', 'defense', 'physicality', 'hits', 'left_stick', 'striker', 'right_stick', 'left_wing', 'left_forward', 'centre_forward', 'right_forward', 'right_wing', 'left_attacking_midfield', 'center_attacking_midfielder', 'right_attacking_midfielder', 'linesman', 'left_centre_midfield', 'central_midfielder', 'right_centre_midfield', 'right_midfielder', 'left_wing_back', 'left_defensive_midfielder', 'center_defensive_midfielder', 'right_defensive_midfielder', 'right_wing_back', 'left_back', 'left_center_back', 'center_back', 'right_center_back', 'right_back', 'goalkeeper', 'gender']

# 2.2 Observing some variables

In [9]:
df.gender.unique() # all players are male so I can drop this column

array(['Male'], dtype=object)

In [10]:
# Noticed 2 dribbling columns and wanted to check if they are the same
df[["dribbling", "dribbling2"]].head(10)

   dribbling  dribbling2
0         73          71
1         69          69
2         79          77
3         68          69
4         85          85
5         67          67
6         77          77
7         77          77
8         44          53
9         75          79

In [11]:
len(df[df.dribbling != df.dribbling2]) # columns are not equal

14347

In [12]:
# Checking df info for nulls, dtypes
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17125 entries, 0 to 17124
Data columns (total 107 columns):
 #    Column                       Non-Null Count  Dtype
---   ------                       --------------  -----
 0    id                           17125 non-null  int64
 1    name                         17125 non-null  object
 2    age                          17125 non-null  int64
 3    overall                      17125 non-null  int64
 4    nationality                  17125 non-null  object
 5    club                         17102 non-null  object
 6    best_overall                 17125 non-null  int64
 7    best_position                17125 non-null  object
 8    position                     16712 non-null  object
 9    player_photo                 17125 non-null  object
 10   club_logo                    17102 non-null  object
 11   flag_photo                   17125 non-null  object
 12   potential                    17125 non-null  int64
 13   team_&_contract              17125 non-null  object
 14   height                       17125 non-null  object
 15   weight                       17125 non-null  object
 16   foot                         17125 non-null  object
 17   growth                       17125 non-null  int64
 18   joined                       17067 non-null  object
 19   loan_date_end                910 non-null    object
 20   value                        17125 non-null  object
 21   wage                         17125 non-null  object
 22   release_clause               17125 non-null  object
 23   contract                     17125 non-null  object
 24   attacking                    17125 non-null  int64
 25   crossing                     17125 non-null  int64
 26   finishing                    17125 non-null  int64
 27   heading_accuracy             17125 non-null  int64
 28   short_passing                17125 non-null  int64
 29   volleys                      17067 non-null  float64
 30   skill                        17125 non-null  int64
 31   dribbling                    17125 non-null  int64
 32   curve                        17067 non-null  float64
 33   free_kick_acc                17125 non-null  int64
 34   long_passing                 17125 non-null  int64
 35   ball_control                 17125 non-null  int64
 36   movement                     17125 non-null  int64
 37   acceleration                 17125 non-null  int64
 38   sprint_speed                 17125 non-null  int64
 39   agility                      17067 non-null  float64
 40   reactions                    17125 non-null  int64
 41   balance                      17067 non-null  float64
 42   power                        17125 non-null  int64
 43   shot_power                   17125 non-null  int64
 44   jumping                      17067 non-null  float64
 45   stamina                      17125 non-null  int64
 46   strength                     17125 non-null  int64
 47   long_shots                   17125 non-null  int64
 48   mentality                    17125 non-null  int64
 49   aggression                   17125 non-null  int64
 50   interceptions                17118 non-null  float64
 51   positioning                  17118 non-null  float64
 52   vision                       17067 non-null  float64
 53   penalties                    17125 non-null  int64
 54   composure                    16702 non-null  float64
 55   defending                    17125 non-null  int64
 56   marking                      17125 non-null  int64
 57   standing_tackle              17125 non-null  int64
 58   sliding_tackle               17067 non-null  float64
 59   goalkeeping                  17125 non-null  int64
 60   gk_diving                    17125 non-null  int64
 61   gk_handling                  17125 non-null  int64
 62   gk_kicking                   17125 non-null  int64
 63   gk_positioning               17125 non-null  int64
 64   gk_reflexes                  17125 non-null  int64
 65   total_stats                  17125 non-null  int64
 66   base_stats                   17125 non-null  int64
 67   weak_foot                    17125 non-null  object
 68   skill_moves                  17125 non-null  object
 69   away_win                     17036 non-null  object
 70   duels_won                    17036 non-null  object
 71   international_reputation     17125 non-null  object
 72   pace                         17125 non-null  int64
 73   shooting                     17125 non-null  int64
 74   passing                      17125 non-null  int64
 75   dribbling2                   17125 non-null  int64
 76   defense                      17125 non-null  int64
 77   physicality                  17125 non-null  int64
 78   hits                         17125 non-null  object
 79   left_stick                   17125 non-null  object
 80   striker                      17125 non-null  object
 81   right_stick                  17125 non-null  object
 82   left_wing                    17125 non-null  object
 83   left_forward                 17125 non-null  object
 84   centre_forward               17125 non-null  object
 85   right_forward                17125 non-null  object
 86   right_wing                   17125 non-null  object
 87   left_attacking_midfield      17125 non-null  object
 88   center_attacking_midfielder  17125 non-null  object
 89   right_attacking_midfielder   17125 non-null  object
 90   linesman                     17125 non-null  object
 91   left_centre_midfield         17125 non-null  object
 92   central_midfielder           17125 non-null  object
 93   right_centre_midfield        17125 non-null  object
 94   right_midfielder             17125 non-null  object
 95   left_wing_back               17125 non-null  object
 96   left_defensive_midfielder    17125 non-null  object
 97   center_defensive_midfielder  17125 non-null  object
 98   right_defensive_midfielder   17125 non-null  object
 99   right_wing_back              17125 non-null  object
 100  left_back                    17125 non-null  object
 101  left_center_back             17125 non-null  object
 102  center_back                  17125 non-null  object
 103  right_center_back            17125 non-null  object
 104  right_back                   17125 non-null  object
 105  goalkeeper                   17125 non-null  object
 106  gender                       17125 non-null  object
dtypes: float64(10), int64(45), object(52)
memory usage: 14.0+ MB

Anomalies detected above:

Following date columns are considered objects instead of numbers:

height
weight
value
wage
release clause

Following date columns are considered objects intead of datetime

joined
loan_date_end
contract (year, duration)

Ratings are considered objects because values have a star symbol in the cell:

weak foot
skill moves
international rating

1st columns drop: Following columns will be dropped:

columns 79 to 105 which consist of values with + sign. These columns are stats of each player for each position.
all images columns: player_photo, club_logo, flag_photo
gender: all are male

In [13]:
# new df with columns 79 to 106 dropped
df = df.iloc[:, :79]
df.head()

,id,name,age,overall,nationality,club,best_overall,best_position,position,player_photo,club_logo,flag_photo,potential,team_&_contract,height,weight,foot,growth,joined,loan_date_end,value,wage,release_clause,contract,attacking,crossing,finishing,heading_accuracy,short_passing,volleys,skill,dribbling,curve,free_kick_acc,long_passing,ball_control,movement,acceleration,sprint_speed,agility,reactions,balance,power,shot_power,jumping,stamina,strength,long_shots,mentality,aggression,interceptions,positioning,vision,penalties,composure,defending,marking,standing_tackle,sliding_tackle,goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,total_stats,base_stats,weak_foot,skill_moves,away_win,duels_won,international_reputation,pace,shooting,passing,dribbling2,defense,physicality,hits
0,2,G. Pasquale,33,69,Italy,Udinese,71,LWB,LM,https://cdn.sofifa.com/players/000/002/16_120.png,https://cdn.sofifa.com/teams/55/light_60.png,https://cdn.sofifa.com/flags/it.png,69,Udinese 2008 ~ 2016,"6'0""",181lbs,Left,0,"Jul 1, 2008",NaN,€625K,€7K,€0,2008 ~ 2016,313,75,50,59,71,58.0,338,73,65.0,60,69,71,347,68,74,68.0,69,68.0,347,74,68.0,69,68,68,320,72,69.0,63.0,66.0,50,NaN,208,70,69,69.0,56,14,5,15,10,12,1929,408,3 ★,2★,Medium,High,2 ★,71,59,70,71,68,69,4
1,16,Luis García,37,71,Spain,KAS Eupen,70,CM,CM CAM CDM,https://cdn.sofifa.com/players/000/016/19_120.png,https://cdn.sofifa.com/teams/2013/light_60.png,https://cdn.sofifa.com/flags/es.png,71,KAS Eupen 2014 ~ 2019,"5'10""",143lbs,Right,0,"Jul 19, 2014",NaN,€600K,€7K,€1.1M,2014 ~ 2019,337,68,64,61,76,68.0,369,69,79.0,79,71,71,305,56,50,62.0,65,72.0,324,75,54.0,64,60,71,362,71,71.0,72.0,73.0,75,79.0,153,70,43,40.0,56,9,12,13,11,11,1906,385,4 ★,3★,Medium,Medium,1 ★,53,69,73,69,58,63,4
2,27,J. Cole,33,71,England,Coventry City,71,CAM,CAM RM RW LM,https://cdn.sofifa.com/players/000/027/16_120.png,https://cdn.sofifa.com/teams/1800/light_60.png,https://cdn.sofifa.com/flags/gb-eng.png,71,Coventry City 2016 ~ 2020,"5'9""",161lbs,Right,0,"Jan 7, 2016",NaN,€1.1M,€15K,€0,2016 ~ 2020,337,80,64,41,77,75.0,387,79,84.0,77,69,78,295,48,42,71.0,59,75.0,284,72,58.0,29,56,69,317,69,39.0,69.0,74.0,66,NaN,99,35,34,30.0,51,9,6,13,16,7,1770,354,4 ★,4★,Medium,Low,2 ★,45,68,76,77,36,52,11
3,36,D. Yorke,36,68,Trinidad &amp; Tobago,Sunderland,70,ST,NaN,https://cdn.sofifa.com/players/000/036/09_120.png,https://cdn.sofifa.com/teams/106/light_60.png,https://cdn.sofifa.com/flags/tt.png,82,Sunderland 2009,"5'11""",165lbs,Right,14,NaN,NaN,€0,€0,€0,2009,264,54,70,60,80,NaN,255,68,NaN,46,64,77,176,59,62,NaN,55,NaN,239,63,NaN,51,66,59,271,59,70.0,72.0,NaN,70,NaN,75,34,41,NaN,68,5,21,64,21,21,1348,369,3 ★,1★,NaN,NaN,1 ★,61,66,66,69,47,60,3
4,41,Iniesta,36,81,Spain,Vissel Kobe,82,CAM,CM CAM,https://cdn.sofifa.com/players/000/041/20_120.png,https://cdn.sofifa.com/teams/101146/light_60.png,https://cdn.sofifa.com/flags/es.png,81,Vissel Kobe 2018 ~ 2021,"5'7""",150lbs,Right,0,"Jul 16, 2018",NaN,€5.5M,€12K,€7.2M,2018 ~ 2021,367,75,69,54,90,79.0,408,85,80.0,70,83,90,346,61,56,79.0,75,75.0,297,67,40.0,58,62,70,370,58,70.0,78.0,93.0,71,89.0,181,68,57,56.0,45,6,13,6,13,7,2014,420,4 ★,4★,High,Medium,4 ★,58,70,85,85,63,59,149

In [14]:
image = ['player_photo', 'club_logo', 'flag_photo']
df.drop(columns= image, axis=1, inplace=True)
df.head()

,id,name,age,overall,nationality,club,best_overall,best_position,position,potential,team_&_contract,height,weight,foot,growth,joined,loan_date_end,value,wage,release_clause,contract,attacking,crossing,finishing,heading_accuracy,short_passing,volleys,skill,dribbling,curve,free_kick_acc,long_passing,ball_control,movement,acceleration,sprint_speed,agility,reactions,balance,power,shot_power,jumping,stamina,strength,long_shots,mentality,aggression,interceptions,positioning,vision,penalties,composure,defending,marking,standing_tackle,sliding_tackle,goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,total_stats,base_stats,weak_foot,skill_moves,away_win,duels_won,international_reputation,pace,shooting,passing,dribbling2,defense,physicality,hits
0,2,G. Pasquale,33,69,Italy,Udinese,71,LWB,LM,69,Udinese 2008 ~ 2016,"6'0""",181lbs,Left,0,"Jul 1, 2008",NaN,€625K,€7K,€0,2008 ~ 2016,313,75,50,59,71,58.0,338,73,65.0,60,69,71,347,68,74,68.0,69,68.0,347,74,68.0,69,68,68,320,72,69.0,63.0,66.0,50,NaN,208,70,69,69.0,56,14,5,15,10,12,1929,408,3 ★,2★,Medium,High,2 ★,71,59,70,71,68,69,4
1,16,Luis García,37,71,Spain,KAS Eupen,70,CM,CM CAM CDM,71,KAS Eupen 2014 ~ 2019,"5'10""",143lbs,Right,0,"Jul 19, 2014",NaN,€600K,€7K,€1.1M,2014 ~ 2019,337,68,64,61,76,68.0,369,69,79.0,79,71,71,305,56,50,62.0,65,72.0,324,75,54.0,64,60,71,362,71,71.0,72.0,73.0,75,79.0,153,70,43,40.0,56,9,12,13,11,11,1906,385,4 ★,3★,Medium,Medium,1 ★,53,69,73,69,58,63,4
2,27,J. Cole,33,71,England,Coventry City,71,CAM,CAM RM RW LM,71,Coventry City 2016 ~ 2020,"5'9""",161lbs,Right,0,"Jan 7, 2016",NaN,€1.1M,€15K,€0,2016 ~ 2020,337,80,64,41,77,75.0,387,79,84.0,77,69,78,295,48,42,71.0,59,75.0,284,72,58.0,29,56,69,317,69,39.0,69.0,74.0,66,NaN,99,35,34,30.0,51,9,6,13,16,7,1770,354,4 ★,4★,Medium,Low,2 ★,45,68,76,77,36,52,11
3,36,D. Yorke,36,68,Trinidad &amp; Tobago,Sunderland,70,ST,NaN,82,Sunderland 2009,"5'11""",165lbs,Right,14,NaN,NaN,€0,€0,€0,2009,264,54,70,60,80,NaN,255,68,NaN,46,64,77,176,59,62,NaN,55,NaN,239,63,NaN,51,66,59,271,59,70.0,72.0,NaN,70,NaN,75,34,41,NaN,68,5,21,64,21,21,1348,369,3 ★,1★,NaN,NaN,1 ★,61,66,66,69,47,60,3
4,41,Iniesta,36,81,Spain,Vissel Kobe,82,CAM,CM CAM,81,Vissel Kobe 2018 ~ 2021,"5'7""",150lbs,Right,0,"Jul 16, 2018",NaN,€5.5M,€12K,€7.2M,2018 ~ 2021,367,75,69,54,90,79.0,408,85,80.0,70,83,90,346,61,56,79.0,75,75.0,297,67,40.0,58,62,70,370,58,70.0,78.0,93.0,71,89.0,181,68,57,56.0,45,6,13,6,13,7,2014,420,4 ★,4★,High,Medium,4 ★,58,70,85,85,63,59,149

In [15]:
# new df0 shape
print("Number of rows: ", df.shape[0])
print("Number of columns: ", df.shape[1])

Number of rows:  17125
Number of columns:  76

    Check for duplicates and missing values

In [16]:
# Checking for missing values
df.isna().sum()

id                              0
name                            0
age                             0
overall                         0
nationality                     0
club                           23
best_overall                    0
best_position                   0
position                      413
potential                       0
team_&_contract                 0
height                          0
weight                          0
foot                            0
growth                          0
joined                         58
loan_date_end               16215
value                           0
wage                            0
release_clause                  0
contract                        0
attacking                       0
crossing                        0
finishing                       0
heading_accuracy                0
short_passing                   0
volleys                        58
skill                           0
dribbling                       0
curve                          58
free_kick_acc                   0
long_passing                    0
ball_control                    0
movement                        0
acceleration                    0
sprint_speed                    0
agility                        58
reactions                       0
balance                        58
power                           0
shot_power                      0
jumping                        58
stamina                         0
strength                        0
long_shots                      0
mentality                       0
aggression                      0
interceptions                   7
positioning                     7
vision                         58
penalties                       0
composure                     423
defending                       0
marking                         0
standing_tackle                 0
sliding_tackle                 58
goalkeeping                     0
gk_diving                       0
gk_handling                     0
gk_kicking                      0
gk_positioning                  0
gk_reflexes                     0
total_stats                     0
base_stats                      0
weak_foot                       0
skill_moves                     0
away_win                       89
duels_won                      89
international_reputation        0
pace                            0
shooting                        0
passing                         0
dribbling2                      0
defense                         0
physicality                     0
hits                            0
dtype: int64

In [17]:
df.duplicated().sum()

0

No duplicates were found. There are missing values but I will deal with them after cleaning the dataset.

# 2.3. Creating subsets and Data Cleaning

I am creating 3 subsets from the full data set so can analyze a group of variables. I will keep the player id column in each subset for merging purposes later on.

df1_full= EA Sports FIFA 19 Game:


Player id
Player Name
Club of the Player
Best Position
Best Overall
Position
Overall
Pace
Shooting
Passing
Dribbling
Defending
Physical
Hits

In [18]:
df1_full = df[['id', 'name', 'club', 'best_position', 'best_overall', 'position', 'overall', 'pace', 'shooting',
               'passing', 'dribbling2','defense', 'physicality','hits']]
df1_full.head()

,id,name,club,best_position,best_overall,position,overall,pace,shooting,passing,dribbling2,defense,physicality,hits
0,2,G. Pasquale,Udinese,LWB,71,LM,69,71,59,70,71,68,69,4
1,16,Luis García,KAS Eupen,CM,70,CM CAM CDM,71,53,69,73,69,58,63,4
2,27,J. Cole,Coventry City,CAM,71,CAM RM RW LM,71,45,68,76,77,36,52,11
3,36,D. Yorke,Sunderland,ST,70,NaN,68,61,66,66,69,47,60,3
4,41,Iniesta,Vissel Kobe,CAM,82,CM CAM,81,58,70,85,85,63,59,149

In [19]:
df1_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17125 entries, 0 to 17124
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             17125 non-null  int64
 1   name           17125 non-null  object
 2   club           17102 non-null  object
 3   best_position  17125 non-null  object
 4   best_overall   17125 non-null  int64
 5   position       16712 non-null  object
 6   overall        17125 non-null  int64
 7   pace           17125 non-null  int64
 8   shooting       17125 non-null  int64
 9   passing        17125 non-null  int64
 10  dribbling2     17125 non-null  int64
 11  defense        17125 non-null  int64
 12  physicality    17125 non-null  int64
 13  hits           17125 non-null  object
dtypes: int64(9), object(5)
memory usage: 1.8+ MB

I observed that the hits column is considered as an object so it needs to be cleaned.

In [20]:
# replacing K in hits column with 000 to create values in thousands and convert it to float
df1_full['hits'] = df1_full['hits'].str.replace('K', '000', regex=True).astype(float)

/var/folders/mm/cjv4cnl90rz3rsp85pkv7wk80000gp/T/ipykernel_57850/2007308317.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_full['hits'] = df1_full['hits'].str.replace('K', '000', regex=True).astype(float)

In [21]:
df1_full.hits.sample(10)

4479      14.0
6040       4.0
5134      11.0
15526      3.0
14567      3.0
12164     21.0
609        3.0
1584       8.0
4312      11.0
4605     182.0
Name: hits, dtype: float64

After cleaning the first subset, I decided to keep the following variables for predicting market value:

In [22]:
df1 = df1_full[['id', 'name', 'club', 'best_position', 'best_overall', 'pace', 'shooting', 'passing', 'dribbling2', 'defense', 'physicality', 'hits']]
df1.head()

,id,name,club,best_position,best_overall,pace,shooting,passing,dribbling2,defense,physicality,hits
0,2,G. Pasquale,Udinese,LWB,71,71,59,70,71,68,69,4.0
1,16,Luis García,KAS Eupen,CM,70,53,69,73,69,58,63,4.0
2,27,J. Cole,Coventry City,CAM,71,45,68,76,77,36,52,11.0
3,36,D. Yorke,Sunderland,ST,70,61,66,66,69,47,60,3.0
4,41,Iniesta,Vissel Kobe,CAM,82,58,70,85,85,63,59,149.0

In [23]:
df1.dtypes

id                 int64
name              object
club              object
best_position     object
best_overall       int64
pace               int64
shooting           int64
passing            int64
dribbling2         int64
defense            int64
physicality        int64
hits             float64
dtype: object

df2_full = Transfermarkt and extra info by player

Player id
Age
Nationality
Height
Foot
Day Joined the current club
Day of Contract End
Market Value of the Player

In [24]:
df2_full = df[['id', 'age', 'nationality',  'team_&_contract', 'height', 'weight', 'foot', 'weak_foot', 'skill_moves',
               'joined', 'loan_date_end', 'value', 'wage', 'release_clause', 'contract',  'potential','away_win',
               'duels_won', 'international_reputation']]
df2_full.head()

,id,age,nationality,team_&_contract,height,weight,foot,weak_foot,skill_moves,joined,loan_date_end,value,wage,release_clause,contract,potential,away_win,duels_won,international_reputation
0,2,33,Italy,Udinese 2008 ~ 2016,"6'0""",181lbs,Left,3 ★,2★,"Jul 1, 2008",NaN,€625K,€7K,€0,2008 ~ 2016,69,Medium,High,2 ★
1,16,37,Spain,KAS Eupen 2014 ~ 2019,"5'10""",143lbs,Right,4 ★,3★,"Jul 19, 2014",NaN,€600K,€7K,€1.1M,2014 ~ 2019,71,Medium,Medium,1 ★
2,27,33,England,Coventry City 2016 ~ 2020,"5'9""",161lbs,Right,4 ★,4★,"Jan 7, 2016",NaN,€1.1M,€15K,€0,2016 ~ 2020,71,Medium,Low,2 ★
3,36,36,Trinidad &amp; Tobago,Sunderland 2009,"5'11""",165lbs,Right,3 ★,1★,NaN,NaN,€0,€0,€0,2009,82,NaN,NaN,1 ★
4,41,36,Spain,Vissel Kobe 2018 ~ 2021,"5'7""",150lbs,Right,4 ★,4★,"Jul 16, 2018",NaN,€5.5M,€12K,€7.2M,2018 ~ 2021,81,High,Medium,4 ★

In [25]:
df2_full.dtypes

id                           int64
age                          int64
nationality                 object
team_&_contract             object
height                      object
weight                      object
foot                        object
weak_foot                   object
skill_moves                 object
joined                      object
loan_date_end               object
value                       object
wage                        object
release_clause              object
contract                    object
potential                    int64
away_win                    object
duels_won                   object
international_reputation    object
dtype: object

I can see several columns need to be cleaned in this subset such as:

Replacing values in the following columns:
nationality : "&" to "and"
height : convert from inches to cm, rename column to height_cm, then change column type to number
weight : could also be converted from pounds to kg, remove lbs and change column name to weight_kg, then change column type to number
weak_foot, skill_moves, and international_reputation : delete star symbol transform columns to integer
joined and loan_date_end : transform to datetime format
contract : separate start and end of contract to 2 columns
value and wage : remove € signs, replace K to thousands value, M to millions value, transform columns to float
Delete columns:
team & contract : already have the club and contract columns which provide the same information

In [26]:
# Selected columns
df2 = df2_full[['id', 'age', 'nationality', 'wage', 'potential', 'value']]
df2.head()

   id  age            nationality  wage  potential  value
0   2   33                  Italy   €7K         69  €625K
1  16   37                  Spain   €7K         71  €600K
2  27   33                England  €15K         71  €1.1M
3  36   36  Trinidad &amp; Tobago    €0         82     €0
4  41   36                  Spain  €12K         81  €5.5M

Clean wage column

In [27]:
# remove euro sign, replace K to 000, then convert to float dtype
df2['wage'] = df2['wage'].str.replace('€', '', regex=True).replace('K', '000', regex=True).astype(float)

/var/folders/mm/cjv4cnl90rz3rsp85pkv7wk80000gp/T/ipykernel_57850/3073949810.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['wage'] = df2['wage'].str.replace('€', '', regex=True).replace('K', '000', regex=True).astype(float)

In [28]:
# check
df2.wage.head()

0     7000.0
1     7000.0
2    15000.0
3        0.0
4    12000.0
Name: wage, dtype: float64

In [29]:
df2.wage.sort_values(ascending=False).head()

752     560000.0
2871    370000.0
1800    350000.0
946     350000.0
1753    310000.0
Name: wage, dtype: float64

Clean value column

In [30]:
# remove € sign
df2['value'] = df2['value'].str.replace('€', '', regex=True)

/var/folders/mm/cjv4cnl90rz3rsp85pkv7wk80000gp/T/ipykernel_57850/1115926971.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['value'] = df2['value'].str.replace('€', '', regex=True)

In [31]:
# function to clean the value column
def clean_value(x):
    if x.endswith('M'):
        return float(x.replace('M', '')) * 1000000
    elif x.endswith('K'):
        return float(x.replace('K', '')) * 1000
    else:
        return float(x)

In [32]:
# apply function and check
df2['value'] = df2['value'].apply(clean_value)
df2['value'].head()

/var/folders/mm/cjv4cnl90rz3rsp85pkv7wk80000gp/T/ipykernel_57850/877536350.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['value'] = df2['value'].apply(clean_value)

0     625000.0
1     600000.0
2    1100000.0
3          0.0
4    5500000.0
Name: value, dtype: float64

In [33]:
df2.value.sort_values(ascending=False).head()

9331    105500000.0
2650     90000000.0
2871     87000000.0
2287     80000000.0
5030     78000000.0
Name: value, dtype: float64

Clean nationality column

In [34]:
df2['nationality'] = df2['nationality'].str.replace('&amp;', 'and') # replace '&amp;' to 'and'
df2[df2.nationality.str.contains('\sand\s')] #check all values containing 'and'

/var/folders/mm/cjv4cnl90rz3rsp85pkv7wk80000gp/T/ipykernel_57850/1677211945.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['nationality'] = df2['nationality'].str.replace('&amp;', 'and') # replace '&amp;' to 'and'

           id  age            nationality     wage  potential      value
3          36   36    Trinidad and Tobago      0.0         82        0.0
697    156166   30    Antigua and Barbuda   5000.0         65   500000.0
769    158525   32    Trinidad and Tobago   3000.0         66   525000.0
2801   192495   28  Saint Kitts and Nevis  59000.0         73  4000000.0
3269   197930   29    Antigua and Barbuda   3000.0         61   250000.0
4538   205425   33  São Tomé and Príncipe  13000.0         70  1100000.0
5578   211966   24    Antigua and Barbuda   8000.0         76  2800000.0
5834   213156   24    Antigua and Barbuda   2000.0         66   325000.0
6558   217852   30    Trinidad and Tobago   6000.0         71  2200000.0
8065   226203   28    Trinidad and Tobago   7000.0         72  3100000.0
8598   229153   22    Trinidad and Tobago    500.0         75  1400000.0
10352  235773   22    Antigua and Barbuda   2000.0         72   500000.0
10368  235830   22    Antigua and Barbuda   2000.0         61    80000.0
13998  247448   26    Trinidad and Tobago    950.0         55    45000.0
14335  250740   18    Antigua and Barbuda    600.0         70   100000.0

df3_full = Player Stats
ATTACKING
Crossing
Finishing
Heading Accuracy
Short Passing
Volleys
SKILL
Dribbling
Curve
FK Accuracy
Long Passing
Ball Control
MOVEMENT
Acceleration
Sprint Speed
Agility
Reactions
Balance
POWER
Shot Power
Jumping
Stamina
Strength
Long Shots
MENTALITY
Aggression
Interceptions
Positioning
Vision
Penalties
Composure
DEFENDING
Defensive Awareness
Standing Tackle
Sliding Tackle
GOALKEEPING
GK Diving
GK Handling
GK Kicking
GK Positioning
GK Reflexes
Growth
Base Stats
Total Stats

Using the sofifa ressource, it's known that there are 7 main categories containing several subcategories. Therefore, the following steps would consist of:

Creating the subset containing player stats and growth column
Checking for dtypes (expecting to only have numbers)
Observing certain variables like growth and base stats to try and find out what they signify
Checking if subcategories add up to the same values in the main categories
Checking if the sum of main category values is equal to the total_stats column

Creating the subset containing player stats and growth column

In [35]:
# list of columns for df3
cols_df3 = ['id', 'growth', 'base_stats', 'total_stats',
            'attacking', 'crossing', 'finishing', 'heading_accuracy','short_passing', 'volleys',
            'skill', 'dribbling', 'curve', 'free_kick_acc', 'long_passing', 'ball_control',
            'movement', 'acceleration', 'sprint_speed', 'agility', 'reactions', 'balance',
            'power', 'shot_power', 'jumping', 'stamina', 'strength', 'long_shots',
            'mentality', 'aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure',
            'defending', 'marking', 'standing_tackle', 'sliding_tackle',
            'goalkeeping', 'gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes']

In [36]:
# create subset
df3_full = df[cols_df3]
df3_full.head()

,id,growth,base_stats,total_stats,attacking,crossing,finishing,heading_accuracy,short_passing,volleys,skill,dribbling,curve,free_kick_acc,long_passing,ball_control,movement,acceleration,sprint_speed,agility,reactions,balance,power,shot_power,jumping,stamina,strength,long_shots,mentality,aggression,interceptions,positioning,vision,penalties,composure,defending,marking,standing_tackle,sliding_tackle,goalkeeping,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,2,0,408,1929,313,75,50,59,71,58.0,338,73,65.0,60,69,71,347,68,74,68.0,69,68.0,347,74,68.0,69,68,68,320,72,69.0,63.0,66.0,50,NaN,208,70,69,69.0,56,14,5,15,10,12
1,16,0,385,1906,337,68,64,61,76,68.0,369,69,79.0,79,71,71,305,56,50,62.0,65,72.0,324,75,54.0,64,60,71,362,71,71.0,72.0,73.0,75,79.0,153,70,43,40.0,56,9,12,13,11,11
2,27,0,354,1770,337,80,64,41,77,75.0,387,79,84.0,77,69,78,295,48,42,71.0,59,75.0,284,72,58.0,29,56,69,317,69,39.0,69.0,74.0,66,NaN,99,35,34,30.0,51,9,6,13,16,7
3,36,14,369,1348,264,54,70,60,80,NaN,255,68,NaN,46,64,77,176,59,62,NaN,55,NaN,239,63,NaN,51,66,59,271,59,70.0,72.0,NaN,70,NaN,75,34,41,NaN,68,5,21,64,21,21
4,41,0,420,2014,367,75,69,54,90,79.0,408,85,80.0,70,83,90,346,61,56,79.0,75,75.0,297,67,40.0,58,62,70,370,58,70.0,78.0,93.0,71,89.0,181,68,57,56.0,45,6,13,6,13,7

In [37]:
df3_full.shape

(17125, 45)

Checking for dtypes (expecting to only have numbers)

In [38]:
df3_full.dtypes.value_counts() #correct assumption

int64      35
float64    10
Name: count, dtype: int64

Observing certain variables like growth and base stats to try and find out what they signify
Create new subsets for the next exploration.

In [39]:
# subset main category stats
main_category = ['attacking', 'skill', 'movement', 'power', 'mentality', 'defending', 'goalkeeping']
main_cat = df3_full[main_category]

# subcategories
attack = df3_full[['crossing', 'finishing', 'heading_accuracy','short_passing', 'volleys']]
skill = df3_full[['dribbling', 'curve', 'free_kick_acc', 'long_passing', 'ball_control']]
movement = df3_full[['acceleration', 'sprint_speed', 'agility', 'reactions', 'balance']]
power = df3_full[['shot_power', 'jumping', 'stamina', 'strength', 'long_shots']]
mentality = df3_full[['aggression', 'interceptions', 'positioning', 'vision', 'penalties', 'composure']]
defense = df3_full[['marking', 'standing_tackle', 'sliding_tackle']]
goal= df3_full[['gk_diving', 'gk_handling', 'gk_kicking', 'gk_positioning', 'gk_reflexes']]

# list of all new subcategory df
subcategory = [attack, skill, movement, power, mentality, defense, goal]

In [40]:
df3_full.growth.unique()

array([ 0, 14,  4,  6,  3, 21, 17,  8, 12,  7,  2, 11,  5, 13,  9, 18, 10,
        1, -1, 16, 20, 19, 15, 23, 22, 25, 24, 26])

In [41]:
df3_full[['growth','base_stats', 'total_stats']].head()

   growth  base_stats  total_stats
0       0         408         1929
1       0         385         1906
2       0         354         1770
3      14         369         1348
4       0         420         2014

In [42]:
main_cat.head()

   attacking  skill  movement  power  mentality  defending  goalkeeping
0        313    338       347    347        320        208           56
1        337    369       305    324        362        153           56
2        337    387       295    284        317         99           51
3        264    255       176    239        271         75           68
4        367    408       346    297        370        181           45

In [43]:
main_cat.mean(axis=1).head() # wanted to see if base_stats is the average but it is NOT

0    275.571429
1    272.285714
2    252.857143
3    192.571429
4    287.714286
dtype: float64

After quickly looking at both growth and base_stats columns, still don't know what they mean so I will drop them.

Checking if subcategories add up to the same values in the main categories

In [44]:
# create a function to check
def check_equality(main, i, sub_sum):
    '''This function can be used to check if the sum of the values in the stats subcategories are equal to the value
    in the main category column.
    main = the column pertaining to a main category being compared
    i = index position
    sub_sum = the sum of all columns considered a subcategory of the main
    result = count of True (values are equal) and False (values are not equal)'''
    
    main = main.iloc[:, i]
    sub_sum = sub_sum[i].sum(axis=1)
    result = (main == sub_sum).value_counts()  
    return result

In [45]:
# append to list and transform to dataframe
sum_check = []
    
for i in range(7):
    sum_check.append(check_equality(main_cat,i, subcategory))

In [46]:
def create_dfcheck(var):
    dfcheck = pd.DataFrame(var).T
    dfcheck.columns = main_cat.columns
    dfcheck.fillna(0,inplace=True)
    return dfcheck

In [47]:
df_check = create_dfcheck(sum_check)
df_check

,attacking,skill,movement,power,mentality,defending,goalkeeping
True,17125.0,17125.0,17125.0,17125.0,423.0,17125.0,17067.0
False,0.0,0.0,0.0,0.0,16702.0,0.0,58.0

In [48]:
# checking for null values in the subcategories
nulls = df3_full.isna().sum()
print(nulls[nulls > 0])

volleys            58
curve              58
agility            58
balance            58
jumping            58
interceptions       7
positioning         7
vision             58
composure         423
sliding_tackle     58
dtype: int64

5 out of the 7 main categories are equal to the sum of their subcategories, with the exception of mentality and goalkeeping. For mentality, this could be a result of several missing values in the subcategories. For this reason and for lack of time to delve deeper, we will drop the subcategories and keep the main ones, assuming they are the same.

Checking if the sum of main category values is equal to the total_stats column

In [49]:
(df.total_stats == main_cat.sum(axis=1)).value_counts()

True    17125
Name: count, dtype: int64

totat_stats column is the sum of values in the main categories.

In [50]:
# subsetting to the columns we decided to keep
cols_to_keep = ['id', 'total_stats', 'attacking', 'skill', 'movement', 'power', 'mentality', 'defending', 'goalkeeping']
df3 = df3_full[cols_to_keep]
df3.head()

,id,total_stats,attacking,skill,movement,power,mentality,defending,goalkeeping
0,2,1929,313,338,347,347,320,208,56
1,16,1906,337,369,305,324,362,153,56
2,27,1770,337,387,295,284,317,99,51
3,36,1348,264,255,176,239,271,75,68
4,41,2014,367,408,346,297,370,181,45

In [51]:
# checking for nulls
df3.isna().sum()

id             0
total_stats    0
attacking      0
skill          0
movement       0
power          0
mentality      0
defending      0
goalkeeping    0
dtype: int64

# 2.4. Merging all three subsets

In [52]:
# Joining the subsets into one df
df_all = df1.merge(df2, on ='id').merge(df3, on = 'id')
df_all.head()

#copy
dfall = df_all.copy()

In [53]:
df_all.isna().sum()

id                 0
name               0
club              23
best_position      0
best_overall       0
pace               0
shooting           0
passing            0
dribbling2         0
defense            0
physicality        0
hits             741
age                0
nationality        0
wage               0
potential          0
value              0
total_stats        0
attacking          0
skill              0
movement           0
power              0
mentality          0
defending          0
goalkeeping        0
dtype: int64

In [55]:
# since the are a lot of records, I've decided to simply drop the nulls
df_all = df_all  # Remove the parentheses to assign the DataFrame to the variable
df_all = df_all.dropna()

In [56]:
df_all_shape = df_all.shape
print(df_all_shape)

(16362, 25)

In [57]:
import pandas as pd

# Assuming df_all is a DataFrame object
duplicates = df_all.duplicated().sum()
print(duplicates)

0

In [58]:
# Assuming df_all is a DataFrame object
df_all = df_all[(df_all['wage'] != 0) & (df_all['value'] != 0)]
df_all_shape = df_all.shape
print(df_all_shape)

(15930, 25)